# Site settings
title: CodeIgnition
email: akashs@codeignition.com
url: https://akashkahlon.github.io
description: "Akashdeep Singh Kahlon"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://facebook.com/akash.kahlon.5
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/akashkahlon

port: 8080
# Build settings
markdown: kramdown
permalink: pretty
